In [45]:
using LinearAlgebra
include("LinearSystems.jl")
import .LinearSystems as ls

In [54]:
for j in 4:4
    n = 4*j
    xᵢ = zeros(n+1)
    y = zeros(n+1)

    h = 2/n
    for i in 1:n+1
        xᵢ[i] = -1+(i-1)*h
    end

    V = hcat([xᵢ.^k for k in 0:n]...)
    println("matrice",V)
    k(V) = ls.norma_1(V)*ls.norma_1(inv(V))
    log_k = log(k(V))
    println("n = $n, condizione della matrice di Vandermonde (log): $log_k")
    for l in 1:10
        k = l*10
        function f(x)
            return cos(k*x)
        end
        for i in 1:n+1
            y[i] = f(xᵢ[i])
        end
        println("vettore",y)
        coefficienti = ls.row_pivoting_solution(V, y)
        display(coefficienti)
        termine_noto = ls.row_pivoting_solution(V, y)[1]
        println("n = $n, k = $k, coefficiente di grado 0: $termine_noto")
    end
end

matrice[1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0; 1.0 -0.875 0.765625 -0.669921875 0.586181640625 -0.512908935546875 0.4487953186035156 -0.39269590377807617 0.34360891580581665 -0.30065780133008957 0.2630755761638284 -0.23019112914334983 0.2014172380004311 -0.1762400832503772 0.15421007284408006 -0.13493381373857005 0.1180670870212488; 1.0 -0.75 0.5625 -0.421875 0.31640625 -0.2373046875 0.177978515625 -0.13348388671875 0.1001129150390625 -0.07508468627929688 0.056313514709472656 -0.04223513603210449 0.03167635202407837 -0.023757264018058777 0.017817948013544083 -0.013363461010158062 0.010022595757618546; 1.0 -0.625 0.390625 -0.244140625 0.152587890625 -0.095367431640625 0.059604644775390625 -0.03725290298461914 0.023283064365386963 -0.014551915228366852 0.009094947017729282 -0.0056843418860808015 0.003552713678800501 -0.002220446049250313 0.0013877787807814457 -0.0008673617379884035 0.0005421010862427522; 1.0 -0.5 0.25 -0.125 0.0625 -0.03125 0.015625 

17-element Vector{Float64}:
     0.9999999999999681
    -2.316819455176686e-13
   -49.99961049803974
     9.549694368615747e-13
   416.62847139469085
    -6.234172773970799e-12
 -1387.8790684998817
     3.9781834465576135e-11
  2468.938696144719
    -1.3397647427035856e-10
 -2693.063209838938
     2.3260772693785e-10
  1896.5177392008018
    -1.9848570759872898e-10
  -819.3039411715425
     6.55835057482883e-11
   166.3218517391137

n = 16, k = 10, coefficiente di grado 0: 0.9999999999999681
vettore[0.40808206181339196, 0.2194399632114593, -0.7596879128588213, 0.9977982791785807, -0.8390715290764524, 0.3466353178350258, 0.28366218546322625, -0.8011436155469337, 1.0, -0.8011436155469337, 0.28366218546322625, 0.3466353178350258, -0.8390715290764524, 0.9977982791785807, -0.7596879128588213, 0.2194399632114593, 0.40808206181339196]


17-element Vector{Float64}:
      0.9999999999587352
     -1.299684375108789e-10
   -191.68481616156112
      1.00882784747041e-9
   5836.827967834937
     -9.156798169538944e-9
 -65896.9556597642
      5.841807302830914e-8
 356147.0074023956
     -1.937676569351654e-7
     -1.0188548156983452e6
      3.331066544514284e-7
      1.5730405453314085e6
     -2.821352353868157e-7
     -1.2315396745219172e6
      9.265610360182294e-8
 381458.15807661094

n = 16, k = 20, coefficiente di grado 0: 0.9999999999587352
vettore[0.15425144988758405, 0.43814818743720435, -0.8733046400935156, 0.9950484010363788, -0.7596879128588213, 0.2516896500717544, 0.3466353178350258, -0.8205593573395608, 1.0, -0.8205593573395608, 0.3466353178350258, 0.2516896500717544, -0.7596879128588213, 0.9950484010363788, -0.8733046400935156, 0.43814818743720435, 0.15425144988758405]


17-element Vector{Float64}:
      0.9999999999715379
     -3.430746285903191e-10
   -195.6919618310924
      1.577610967218882e-9
   6063.491446089421
     -1.0173737268125864e-8
 -69424.3966452089
      6.324160065873613e-8
 379345.0095444027
     -2.09917059848141e-7
     -1.094305008587509e6
      3.610139501037762e-7
      1.7001181329686157e6
     -3.058866239521139e-7
     -1.337224747219033e6
      1.0048733396723987e-7
 415622.364705924

n = 16, k = 30, coefficiente di grado 0: 0.9999999999715379
vettore[-0.6669380616522619, -0.9036922050915067, 0.15425144988758405, 0.9912028118634736, 0.40808206181339196, -0.7596879128588213, -0.8390715290764524, 0.28366218546322625, 1.0, 0.28366218546322625, -0.8390715290764524, -0.7596879128588213, 0.40808206181339196, 0.9912028118634736, 0.15425144988758405, -0.9036922050915067, -0.6669380616522619]


17-element Vector{Float64}:
     0.9999999999997568
    -2.314422638034983e-13
   -52.689468420074476
     1.6120210579500939e-12
   462.6486416931772
    -1.1112371628934687e-11
 -1623.7900924179626
     5.807567075266589e-11
  3041.325274453059
    -1.8589465531477047e-10
 -3484.886987665859
     3.2329963298191235e-10
  2564.289805730309
    -2.782569462417918e-10
 -1147.3469904592728
     9.250809065677211e-11
   238.78287902497135

n = 16, k = 40, coefficiente di grado 0: 0.9999999999997568
vettore[0.9649660284921133, 0.9731401278705245, 0.9802426408101081, 0.9862657462824945, 0.9912028118634736, 0.9950484010363788, 0.9977982791785807, 0.9994494182244994, 1.0, 0.9994494182244994, 0.9977982791785807, 0.9950484010363788, 0.9912028118634736, 0.9862657462824945, 0.9802426408101081, 0.9731401278705245, 0.9649660284921133]


17-element Vector{Float64}:
  1.0
 -2.3318977996918333e-16
 -0.03524046760330494
  1.4292520158840298e-14
  0.00020698175915974317
 -3.2013137679228244e-13
 -4.862712380145595e-7
  2.550396287557716e-12
  5.857197220191474e-10
 -9.203810187424296e-12
  8.056103285057347e-11
  1.6459677310641926e-11
 -1.3188296168163954e-10
 -1.4199015016761242e-11
  1.0727200815550936e-10
  4.698823652399307e-12
 -3.417326292659426e-11

n = 16, k = 50, coefficiente di grado 0: 1.0
vettore[-0.9524129804151563, -0.616052331690985, 0.5253219888177297, 0.9802426408101081, 0.15425144988758405, -0.8733046400935156, -0.7596879128588213, 0.3466353178350258, 1.0, 0.3466353178350258, -0.7596879128588213, -0.8733046400935156, 0.15425144988758405, 0.9802426408101081, 0.5253219888177297, -0.616052331690985, -0.9524129804151563]


17-element Vector{Float64}:
     0.999999999999735
     6.881775926953823e-14
   -47.38016511290956
     2.5273458539651565e-13
   374.1260476915987
    -4.778981251134114e-12
 -1181.1777963300087
     3.035773698434808e-11
  1992.6266123819896
    -1.0004587541965218e-10
 -2065.4123768667537
     1.7255513688784568e-10
  1389.2869422809679
    -1.4687995454644474e-10
  -578.3899076338092
     4.847038500037122e-11
   114.36823060850993

n = 16, k = 60, coefficiente di grado 0: 0.999999999999735
vettore[0.6333192030862999, -0.011056519718198895, -0.616052331690985, 0.9731401278705245, -0.9036922050915067, 0.43814818743720435, 0.2194399632114593, -0.7808456836057491, 1.0, -0.7808456836057491, 0.2194399632114593, 0.43814818743720435, -0.9036922050915067, 0.9731401278705245, -0.616052331690985, -0.011056519718198895, 0.6333192030862999]


17-element Vector{Float64}:
       1.0000000000429434
      -9.1101138524026e-11
    -187.59283252795356
       9.423580685017022e-10
    5608.490915687961
      -8.90212587281977e-9
  -62382.88105534187
       5.449451370979923e-8
  333242.6764195393
      -1.781409276748988e-7
 -944882.7149443605
       3.055395062428102e-7
       1.449132958237989e6
      -2.5890032909074857e-7
      -1.1289251431847545e6
       8.505810575588006e-8
  348393.8397629717

n = 16, k = 70, coefficiente di grado 0: 1.0000000000429434
vettore[-0.11038724383904756, 0.6333192030862999, -0.9524129804151563, 0.9649660284921133, -0.6669380616522619, 0.15425144988758405, 0.40808206181339196, -0.8390715290764524, 1.0, -0.8390715290764524, 0.40808206181339196, 0.15425144988758405, -0.6669380616522619, 0.9649660284921133, -0.9524129804151563, 0.6333192030862999, -0.11038724383904756]


17-element Vector{Float64}:
      0.9999999999570924
      2.8600518356222887e-12
   -199.60036986959966
      1.0562967662945783e-9
   6287.404934252981
     -1.2193953752461257e-8
 -72945.55487230245
      7.154601240686886e-8
 402695.81892661424
     -2.2877493778108835e-7
     -1.170753235870727e6
      3.9021970042956623e-7
      1.8295372650878483e6
     -3.30309099676446e-7
     -1.4452833323308148e6
      1.0845312155543029e-7
 450660.1241077546

n = 16, k = 80, coefficiente di grado 0: 0.9999999999570924
vettore[-0.4480736161291702, -0.9779926124309412, -0.04422762066183892, 0.9557293436951722, 0.5253219888177297, -0.6912931286141072, -0.8733046400935156, 0.2516896500717544, 1.0, 0.2516896500717544, -0.8733046400935156, -0.6912931286141072, 0.5253219888177297, 0.9557293436951722, -0.04422762066183892, -0.9779926124309412, -0.4480736161291702]


17-element Vector{Float64}:
     1.0000000000000226
     3.839355914083722e-13
   -55.449709149570005
    -6.031232493487784e-13
   512.3732359129752
    -9.028801948509433e-12
 -1892.079326729612
     6.721598938817069e-11
  3725.599385645551
    -2.309210424152339e-10
 -4476.796806252736
     4.1033101189974603e-10
  3435.482400545683
    -3.5672742259084125e-10
 -1589.198480982101
     1.1934945332460826e-10
   338.6212273936806

n = 16, k = 90, coefficiente di grado 0: 1.0000000000000226
vettore[0.8623188722876839, 0.8940034169437217, 0.9217512697247493, 0.9454402445803316, 0.9649660284921133, 0.9802426408101081, 0.9912028118634736, 0.9977982791785807, 1.0, 0.9977982791785807, 0.9912028118634736, 0.9802426408101081, 0.9649660284921133, 0.9454402445803316, 0.9217512697247493, 0.8940034169437217, 0.8623188722876839]


17-element Vector{Float64}:
  1.0
 -2.7835712588722754e-15
 -0.14096187041326325
  8.235207387813786e-14
  0.003311708152274079
 -9.31543184341252e-13
 -3.112164521581004e-5
  5.213376079849813e-12
  1.5671754748248144e-7
 -1.5558727286773978e-11
 -6.133509924544282e-10
  2.4964927731791832e-11
  1.9949340018419818e-10
 -2.017508864189539e-11
 -1.610609181682378e-10
  6.407486798749709e-12
  5.125989438989139e-11

n = 16, k = 100, coefficiente di grado 0: 1.0


il condition number scala con e^n

In [ ]:
for j in 4:4
    n = 4*j
    xᵢ = zeros(n+1)
    y = zeros(n+1)

    h = 2/n
    for i in 1:n+1
        xᵢ[i] = -1+(i-1)*h
    end

    V = hcat([xᵢ.^k for k in 0:n]...)
    println("matrice",V)
    k(V) = ls.norma_1(V)*ls.norma_1(inv(V))
    log_k = log(k(V))
    println("n = $n, condizione della matrice di Vandermonde (log): $log_k")
    for l in 1:10
        k = l*10
        function f(x)
            return cos(k*x)
        end
        for i in 1:n+1
            y[i] = f(xᵢ[i])
        end
        println("vettore",y)
        coefficienti = ls.QR_less_solution(V, y)
        display(coefficienti)
        termine_noto = ls.QR_less_solution(V, y)[1]
        println("n = $n, k = $k, coefficiente di grado 0: $termine_noto")
    end
end

matrice[1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0 -1.0 1.0; 1.0 -0.875 0.765625 -0.669921875 0.586181640625 -0.512908935546875 0.4487953186035156 -0.39269590377807617 0.34360891580581665 -0.30065780133008957 0.2630755761638284 -0.23019112914334983 0.2014172380004311 -0.1762400832503772 0.15421007284408006 -0.13493381373857005 0.1180670870212488; 1.0 -0.75 0.5625 -0.421875 0.31640625 -0.2373046875 0.177978515625 -0.13348388671875 0.1001129150390625 -0.07508468627929688 0.056313514709472656 -0.04223513603210449 0.03167635202407837 -0.023757264018058777 0.017817948013544083 -0.013363461010158062 0.010022595757618546; 1.0 -0.625 0.390625 -0.244140625 0.152587890625 -0.095367431640625 0.059604644775390625 -0.03725290298461914 0.023283064365386963 -0.014551915228366852 0.009094947017729282 -0.0056843418860808015 0.003552713678800501 -0.002220446049250313 0.0013877787807814457 -0.0008673617379884035 0.0005421010862427522; 1.0 -0.5 0.25 -0.125 0.0625 -0.03125 0.015625 

17-element Vector{Float64}:
   -0.0937118707824354
   -6.49015615731542e-15
   -0.6788917097002455
   -7.652963127381564e-17
   -3.095845898671932
   -3.775518703083898e-15
   -2.243727042560401
    2.2746734352653012e-14
  101.01631780708504
   -3.649459465469495e-13
 -276.21382974970317
   -7.015757114463305e-12
  362.2140825539441
    1.8196650947120857e-9
 -294.51825982917717
   -9.301449901857344e-7
  166.32181765478373

n = 16, k = 10, coefficiente di grado 0: -0.0937118707824354
vettore[0.40808206181339196, 0.2194399632114593, -0.7596879128588213, 0.9977982791785807, -0.8390715290764524, 0.3466353178350258, 0.28366218546322625, -0.8011436155469337, 1.0, -0.8011436155469337, 0.28366218546322625, 0.3466353178350258, -0.8390715290764524, 0.9977982791785807, -0.7596879128588213, 0.2194399632114593, 0.40808206181339196]


17-element Vector{Float64}:
      0.04184879411246944
      8.434238789112747e-12
      0.2634786673429546
      4.2250428383839665e-17
      1.0635008273987536
      2.155949842559207e-12
      3.086016566031431
      9.715883702446469e-11
     -0.6645615074819771
     -1.1371620925028164e-10
   -140.3265666715334
      2.4026516155078498e-11
  -2164.5678186457026
     -1.0191574903337089e-9
 -27946.8975261347
      3.247124770262839e-7
 381458.15811268473

n = 16, k = 20, coefficiente di grado 0: 0.04184879411246944
vettore[0.15425144988758405, 0.43814818743720435, -0.8733046400935156, 0.9950484010363788, -0.7596879128588213, 0.2516896500717544, 0.3466353178350258, -0.8205593573395608, 1.0, -0.8205593573395608, 0.3466353178350258, 0.2516896500717544, -0.7596879128588213, 0.9950484010363788, -0.8733046400935156, 0.43814818743720435, 0.15425144988758405]


17-element Vector{Float64}:
      0.027320128930189827
      9.18892145949489e-12
      0.16316157383072658
      5.4272211394789547e-17
      0.5491102886985173
      2.01501744427335e-12
      0.5586510382898467
      1.0555668071529194e-10
    -12.90156156736934
     -1.2411069815362734e-10
   -195.58268430731349
      2.5208635680361702e-11
  -2314.9549993132105
     -7.179656357233802e-10
 -25835.6327739084
      1.850399786079043e-7
 415622.3647324918

n = 16, k = 30, coefficiente di grado 0: 0.027320128930189827
vettore[-0.6669380616522619, -0.9036922050915067, 0.15425144988758405, 0.9912028118634736, 0.40808206181339196, -0.7596879128588213, -0.8390715290764524, 0.28366218546322625, 1.0, 0.28366218546322625, -0.8390715290764524, -0.7596879128588213, 0.40808206181339196, 0.9912028118634736, 0.15425144988758405, -0.9036922050915067, -0.6669380616522619]


17-element Vector{Float64}:
   -0.09790484701781263
   -6.828185461329301e-15
   -0.661130978222712
    2.5177859736869784e-18
   -2.543989716425164
   -2.7123824653263203e-15
    1.5463899065665994
    3.979882031063133e-14
   99.24703368325693
   -3.6115735049672487e-13
 -311.78503749249376
   -6.368722049945468e-12
  448.29324850157263
    1.703934747851299e-9
 -393.9292371467043
   -8.975313440222012e-7
  238.7828577054256

n = 16, k = 40, coefficiente di grado 0: -0.09790484701781263
vettore[0.9649660284921133, 0.9731401278705245, 0.9802426408101081, 0.9862657462824945, 0.9912028118634736, 0.9950484010363788, 0.9977982791785807, 0.9994494182244994, 1.0, 0.9994494182244994, 0.9977982791785807, 0.9950484010363788, 0.9912028118634736, 0.9862657462824945, 0.9802426408101081, 0.9731401278705245, 0.9649660284921133]


17-element Vector{Float64}:
  0.9868368769127263
 -1.4689514783663382e-17
 -0.035043615120530065
  1.5188934746091375e-16
  0.00020626100358102063
 -9.409528731028537e-16
 -4.850721025288205e-7
  7.806091160773804e-15
  6.131863900861383e-10
 -2.9971806773416955e-13
 -2.0372139688243037e-11
  1.5868377494595987e-11
 -8.285225570449517e-10
 -3.9934465141760334e-10
  4.818201101598402e-8
  2.51065209141507e-7
  4.978013723516017e-5

n = 16, k = 50, coefficiente di grado 0: 0.9868368769127263
vettore[-0.9524129804151563, -0.616052331690985, 0.5253219888177297, 0.9802426408101081, 0.15425144988758405, -0.8733046400935156, -0.7596879128588213, 0.3466353178350258, 1.0, 0.3466353178350258, -0.7596879128588213, -0.8733046400935156, 0.15425144988758405, 0.9802426408101081, 0.5253219888177297, -0.616052331690985, -0.9524129804151563]


17-element Vector{Float64}:
   -0.08176546678918167
   -6.061953444207554e-15
   -0.6460601370977788
   -2.991925683730203e-17
   -3.474500842512329
   -4.635559178526028e-15
   -6.109183818289223
    7.011137438781736e-15
  100.66244551445834
   -3.594341270842247e-13
 -241.54239083028324
   -7.246886127704384e-12
  289.1937078132073
    1.7989983147980942e-9
 -217.5304703671805
   -8.92841401693492e-7
  114.36818560961314

n = 16, k = 60, coefficiente di grado 0: -0.08176546678918167
vettore[0.6333192030862999, -0.011056519718198895, -0.616052331690985, 0.9731401278705245, -0.9036922050915067, 0.43814818743720435, 0.2194399632114593, -0.7808456836057491, 1.0, -0.7808456836057491, 0.2194399632114593, 0.43814818743720435, -0.9036922050915067, 0.9731401278705245, -0.616052331690985, -0.011056519718198895, 0.6333192030862999]


17-element Vector{Float64}:
      0.05322361664015142
      7.702179850639047e-12
      0.34451737569958163
     -2.3648906517175247e-17
      1.505814915872105
      2.263195324687781e-12
      5.436381867188626
      8.900135866685207e-11
     11.746732228942175
     -1.0367073310009252e-10
    -78.034983216919
      2.296923109307268e-11
  -1943.8971951263359
     -1.2734578288323253e-9
 -29658.289900353084
      4.3884068399896e-7
 348393.8398074681

n = 16, k = 70, coefficiente di grado 0: 0.05322361664015142
vettore[-0.11038724383904756, 0.6333192030862999, -0.9524129804151563, 0.9649660284921133, -0.6669380616522619, 0.15425144988758405, 0.40808206181339196, -0.8390715290764524, 1.0, -0.8390715290764524, 0.40808206181339196, 0.15425144988758405, -0.6669380616522619, 0.9649660284921133, -0.9524129804151563, 0.6333192030862999, -0.11038724383904756]


17-element Vector{Float64}:
      0.010801050378929242
      9.961165272829048e-12
      0.051388850598723196
      7.010931383451843e-17
      0.00028782830027419034
      1.841739766838092e-12
     -1.979266266782667
      1.1414818225085928e-10
    -24.27657084211646
     -1.347784771812882e-10
   -241.34260942187487
      2.6503556378580623e-11
  -2390.025956664528
     -3.9251857143516053e-10
 -23341.610095642816
      3.0704107793020805e-8
 450660.12412447954

n = 16, k = 80, coefficiente di grado 0: 0.010801050378929242
vettore[-0.4480736161291702, -0.9779926124309412, -0.04422762066183892, 0.9557293436951722, 0.5253219888177297, -0.6912931286141072, -0.8733046400935156, 0.2516896500717544, 1.0, 0.2516896500717544, -0.8733046400935156, -0.6912931286141072, 0.5253219888177297, 0.9557293436951722, -0.04422762066183892, -0.9779926124309412, -0.4480736161291702]


17-element Vector{Float64}:
   -0.09437066298176218
   -6.702456126409228e-15
   -0.59613969356115
   -9.739867890848782e-17
   -1.8579515239731352
   -7.8586279130829505e-16
    5.10008605537525
    6.735235703567626e-14
   95.23595400090798
   -3.764983783376024e-13
 -347.3979289446532
   -5.427828085748617e-12
  548.4342061682484
    1.464838429583576e-9
 -520.766584131845
   -8.006801584959432e-7
  338.6212199227058

n = 16, k = 90, coefficiente di grado 0: -0.09437066298176218
vettore[0.8623188722876839, 0.8940034169437217, 0.9217512697247493, 0.9454402445803316, 0.9649660284921133, 0.9802426408101081, 0.9912028118634736, 0.9977982791785807, 1.0, 0.9977982791785807, 0.9912028118634736, 0.9802426408101081, 0.9649660284921133, 0.9454402445803316, 0.9217512697247493, 0.8940034169437217, 0.8623188722876839]


17-element Vector{Float64}:
  0.9479674781036189
  1.5754900337318574e-17
 -0.13783263078782437
  1.7230590099654294e-16
  0.0032657825000181238
 -8.496774305354987e-16
 -3.081452038257082e-5
  3.935166510938487e-15
  1.555090065339218e-7
 -2.739666769713149e-13
 -5.088367517106516e-10
  1.4858849541747116e-11
 -6.457177313604563e-10
 -1.9463280978677355e-10
  3.136275490368004e-8
  1.3261852911762708e-7
  5.017140505240725e-5

n = 16, k = 100, coefficiente di grado 0: 0.9479674781036189


2. a.

In [48]:
for n in 4:20
    xᵢ = zeros(n+1)

    h = 2/n
    for i in 1:n+1
        xᵢ[i] = -1+(i-1)*h
    end

    V = hcat([xᵢ.^k for k in 0:n]...)
    #println(V)
    k(V) = ls.norma_1(V)*ls.norma_1(inv(V))
    log_k = log(k(V))
    println("n = $n, condizione della matrice di Vandermonde (log): $log_k")
end

n = 4, condizione della matrice di Vandermonde (log): 3.912023005428146
n = 5, condizione della matrice di Vandermonde (log): 5.071259915912691
n = 6, condizione della matrice di Vandermonde (log): 6.12029741895095
n = 7, condizione della matrice di Vandermonde (log): 7.286515102285216
n = 8, condizione della matrice di Vandermonde (log): 8.354674261918463
n = 9, condizione della matrice di Vandermonde (log): 9.51967953794886
n = 10, condizione della matrice di Vandermonde (log): 10.600259751990883
n = 11, condizione della matrice di Vandermonde (log): 11.762596291396106
n = 12, condizione della matrice di Vandermonde (log): 12.85169049174054
n = 13, condizione della matrice di Vandermonde (log): 14.011313247345596
n = 14, condizione della matrice di Vandermonde (log): 15.106556506763718
n = 15, condizione della matrice di Vandermonde (log): 16.263737980948882
n = 16, condizione della matrice di Vandermonde (log): 17.363613227815122
n = 17, condizione della matrice di Vandermonde (log)

2. b. 

In [49]:
for n in 4:20
    m= n+1
    xᵢ = zeros(m)
    
  
    for i in 1:m
        xᵢ[i] = cos((i-1)/(m-1)*π)
    end

    V = hcat([xᵢ.^k for k in 0:n]...)
    #println(V)
    k(V) = ls.norma_1(V)*ls.norma_1(inv(V))
    log_k = log(k(V))
    println("n = $n, condizione della matrice di Vandermonde (log): $log_k")
end

n = 4, condizione della matrice di Vandermonde (log): 3.5305322702935613
n = 5, condizione della matrice di Vandermonde (log): 4.420837913323137
n = 6, condizione della matrice di Vandermonde (log): 5.278114659230518
n = 7, condizione della matrice di Vandermonde (log): 6.112758794105627
n = 8, condizione della matrice di Vandermonde (log): 7.00955626397289
n = 9, condizione della matrice di Vandermonde (log): 7.873470894183829
n = 10, condizione della matrice di Vandermonde (log): 8.74054578359779
n = 11, condizione della matrice di Vandermonde (log): 9.623772423133174
n = 12, condizione della matrice di Vandermonde (log): 10.492273717771429
n = 13, condizione della matrice di Vandermonde (log): 11.370456122364796
n = 14, condizione della matrice di Vandermonde (log): 12.24955023607064
n = 15, condizione della matrice di Vandermonde (log): 13.120890292946822
n = 16, condizione della matrice di Vandermonde (log): 14.003387297208144
n = 17, condizione della matrice di Vandermonde (log):

2. c.

In [69]:
# Funzione per calcolare i polinomi di Legendre fino a grado n in x
function legendre_polynomials(n, x)
    P = zeros(n+1)
    P[1] = 1.0
    if n >= 1
        P[2] = x
        for k in 2:n
            P[k+1] = ((2k - 1)*x*P[k] - (k-1)*P[k-1]) / (k)
        end
    end
    return P
end

# Costruzione della matrice P_n per dato n
function matrix_Plegendre(n, x)

    Pmat = zeros(n + 1, n + 1)
    for i in 1:(n + 1)
        Pmat[i, :] = legendre_polynomials(n, x[i])
    end
    return Pmat
end
x = 1/3
n = 2
legendre_polynomials(n, x)


3-element Vector{Float64}:
  1.0
  0.3333333333333333
 -0.33333333333333337

In [70]:
for n in 4:20
    h = 2/n
    x = zeros(n+1)
    for i in 1:n+1
        x[i] = -1+(i-1)*h
    end
    P = matrix_Plegendre(n, x)
    #println(V)
    kP = ls.norma_1(P)*ls.norma_1(inv(P))
    #log_k = log(k(P))
    println("n = $n, condizione della matrice di Vandermonde: $kP")
end

n = 4, condizione della matrice di Vandermonde: 11.42857142857143
n = 5, condizione della matrice di Vandermonde: 18.948412698412696
n = 6, condizione della matrice di Vandermonde: 24.627272727272736
n = 7, condizione della matrice di Vandermonde: 37.1386622636623
n = 8, condizione della matrice di Vandermonde: 54.01318681318681
n = 9, condizione della matrice di Vandermonde: 89.19212974525486
n = 10, condizione della matrice di Vandermonde: 146.63985252220536
n = 11, condizione della matrice di Vandermonde: 274.6501961682112
n = 12, condizione della matrice di Vandermonde: 499.22226400225213
n = 13, condizione della matrice di Vandermonde: 922.0552641064842
n = 14, condizione della matrice di Vandermonde: 1702.198657245823
n = 15, condizione della matrice di Vandermonde: 3262.2327332061304
n = 16, condizione della matrice di Vandermonde: 5940.600253352518
n = 17, condizione della matrice di Vandermonde: 11578.354176949179
n = 18, condizione della matrice di Vandermonde: 21767.47328251

In [71]:
for n in 4:20
    m= n+1
    zᵢ = zeros(m)
    
    for i in 1:m
        zᵢ[i] = cos((i-1)/(m-1)*π)
    end
    P = matrix_Plegendre(n, zᵢ)
    #println(V)
    kP = ls.norma_1(P)*ls.norma_1(inv(P))
    #log_k = log(k(P))
    println("n = $n, condizione della matrice di Vandermonde: $kP")
end

n = 4, condizione della matrice di Vandermonde: 10.22828282092095
n = 5, condizione della matrice di Vandermonde: 14.654411907846688
n = 6, condizione della matrice di Vandermonde: 17.91245791245791
n = 7, condizione della matrice di Vandermonde: 22.88429752944095
n = 8, condizione della matrice di Vandermonde: 27.036213604388482
n = 9, condizione della matrice di Vandermonde: 32.31093627801051
n = 10, condizione della matrice di Vandermonde: 37.01405339624868
n = 11, condizione della matrice di Vandermonde: 42.77695721455245
n = 12, condizione della matrice di Vandermonde: 47.876793582974244
n = 13, condizione della matrice di Vandermonde: 54.192631723800645
n = 14, condizione della matrice di Vandermonde: 59.71302454921291
n = 15, condizione della matrice di Vandermonde: 66.47929749251163
n = 16, condizione della matrice di Vandermonde: 72.43024691947768
n = 17, condizione della matrice di Vandermonde: 79.58119170070286
n = 18, condizione della matrice di Vandermonde: 85.886753120754